program: scripts/trainer.py
method: grid
project: tuning
metric:
  goal: minimize
  name: val_loss
parameters:
  model.n_hidden_layers:
    values: [5,10,15]

command:
  - ${env}
  - python
  - ${program}
  - fit
  - --config
  - configs/cnn.yaml
  - ${args}