program: scripts/trainer.py
method: grid
project: tuning
metric:
  goal: minimize
  name: val_loss
parameters:
  data.batch_size:
    values: [8,16,32]

command:
  - setup.bash
  - srun
  - python
  - ${program}
  - fit
  - --config
  - configs/kraken_cnn_nemo.yaml
  - ${args}
  - > 
  - results/outputs/${SLURM_JOBID}.out