program: scripts/trainer.py
method: grid
project: tuning
metric:
  goal: minimize
  name: val_loss
parameters:
  model.n_layers:
    values: [5,10,15,20]

command:
  - srun
  - --partition=gpu
  - --nodes=1
  - --ntasks-per-node=1
  - --job-name=train_net
  - --time=12:00:00
  - --output=results/outputs/slurm-%A.%a.out
  - --error=results/outputs/slurm-%A.%a.err
  - python
  - ${program}
  - fit
  - --config
  - configs/kraken_cnn_nemo.yaml
  - ${args}