seed_everything: 42
trainer:
  logger:
    class_path: pytorch_lightning.loggers.WandbLogger
    init_args:
      name: null
      save_dir: results/wandb
      offline: false
      id: null
      anonymous: null
      version: null
      project: nemovar
      log_model: false
      experiment: null
      prefix: ''
      agg_key_funcs: null
      agg_default_func: null
  checkpoint_callback: null
  enable_checkpointing: true
  callbacks:
  - class_path: pytorch_lightning.callbacks.ModelCheckpoint
    init_args:
      dirpath: null
      filename: '{epoch}-{val_loss:.5f}'
      monitor: val_loss
      verbose: false
      save_last: true
      save_top_k: 1
      save_weights_only: false
      mode: min
      auto_insert_metric_name: true
      every_n_train_steps: null
      train_time_interval: null
      every_n_epochs: 1
      save_on_train_epoch_end: true
  default_root_dir: null
  gradient_clip_val: null
  gradient_clip_algorithm: null
  process_position: 0
  num_nodes: 1
  num_processes: null
  devices: null
  gpus: null
  auto_select_gpus: false
  tpu_cores: null
  ipus: null
  log_gpu_memory: null
  progress_bar_refresh_rate: null
  enable_progress_bar: true
  overfit_batches: false
  track_grad_norm: -1
  check_val_every_n_epoch: 1
  fast_dev_run: false
  accumulate_grad_batches: null
  max_epochs: 10000
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  val_check_interval: null
  flush_logs_every_n_steps: null
  log_every_n_steps: 1
  accelerator: auto
  strategy: null
  sync_batchnorm: false
  precision: 32
  enable_model_summary: true
  weights_summary: top
  weights_save_path: null
  num_sanity_val_steps: 2
  resume_from_checkpoint: null
  profiler: null
  benchmark: null
  deterministic: true
  reload_dataloaders_every_n_epochs: 0
  auto_lr_find: false
  replace_sampler_ddp: true
  detect_anomaly: false
  auto_scale_batch_size: false
  prepare_data_per_node: null
  plugins: null
  amp_backend: native
  amp_level: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  stochastic_weight_avg: false
  terminate_on_nan: null
  
model:
  n_channels: 3
  n_classes: 1
  depth: 5
  depth_0_filters: 16
  final_layer_filters: 5
  predict_squared: false
  predict_inverse: false
  optimizer: Adam
  data_transformation: standardize
  norm_layer: Batch
  data_dir: data/processed/nemonemo_perten1190_samples_standardize/
  q: 0.9999
data:
  batch_size: 16
  data_dir: data/processed/nemonemo_perten1190_samples_standardize/
  num_workers: 0
  gpus: 0
ckpt_path: null
